### ISSUE TITLE
Writing a small documentation

### ISSUE THREAD

**Issue by FernandAdam** [KettleMC-Network/DiscordBridge#5]
It would be nice to create a small installation instruction and/or user manual. I could do it if @UeberallGebannt help me.
I could write about:
- Goal:
    - link and verify discord and minecraft accounts
- Dependencies/Version of Minecraft
   - Server information and link to repo
- Installation
- Configuration

Are there important informations missing?

**Comment by LeStegii** [comment]
The plugin is compatible with every version ranging from 1.7.10 to 1.19.2.
It should run on every software supporting Bukkit (CraftBukkit, Spigot, Paper, Magma, Thermos, ...).
The configuration is pretty straigth forward, put it in the plugins folder, restart the server and insert the channel ID of your discord server as well as your bot token into the config.

Maybe we could add a small tutorial on how to create a bot though.

Beside from that, I don't see anything that's missing.

**Comment by FernandAdam** [comment]
So this program will just redirect Minecraft messages to the discord bot? Then the discord bot starts to do something with the messages?

**Comment by LeStegii** [comment]
And vice versa

**Comment by LeStegii** [comment]
Closed in #6
